---
name: docker

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  USER_NAME: bids
  REPO_NAME: giga_connectome
  DATA:  /home/runner/work/giga_connectome/giga_connectome/giga_connectome/data/test_data
  IMAGE: /home/runner/work/giga_connectome/giga_connectome/docker/

jobs:
  download-test-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.DATA }}
        key: data
    - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      uses: actions/setup-python@v5
    - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      name: Download fmriprep derivative of ds000017
      run: |
        pip install tox
        tox -e test_data

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag bids/giga_connectome
          mkdir -p ${{ env.IMAGE }}
          docker save "bids/giga_connectome" > "${{ env.IMAGE }}/image.tar"
          docker images

  docker-run:
    runs-on: ubuntu-latest
    needs: [download-test-data, docker-build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore cached docker image
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.IMAGE }}
          key: docker
      - name: Restore cached data ds000017
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DATA }}
          key: data
      - name: Test the Docker image
        run: |
          docker load -i ${{ env.IMAGE }}/image.tar
          docker run --rm \
            -v ${{ env.DATA }}:/test_data \
            -v ./outputs:/outputs \
            -v ./outputs/working_dir:/work \
              bids/giga_connectome \
                /test_data/ds000017-fmriprep22.0.1-downsampled-nosurface \
                /outputs \
                participant \
                -w /work \
                --participant_label 1 \
                --reindex-bids

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: connectome
          path: ./outputs/

  docker-push:
    runs-on: ubuntu-latest
    needs: [docker-run]
    defaults:
      run:
          shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore cached docker image
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.IMAGE }}
          key: docker
      - name: Load image
        run: docker load -i ${{ env.IMAGE }}/image.tar
      - name: Push unstable to dockerhub on tags or on main
        if:  ${{  github.ref_name }} == "main" || ${{  github.ref_type }} == "tag"
       env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
         DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
       run: |
          if [[ -n "$DOCKERHUB_TOKEN" ]]; then

            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            : "Pushing unstable versions to DockerHub"

            unstable="${{env.USER_NAME}}/${{env.REPO_NAME}}:unstable"

            docker tag "${{env.USER_NAME}}/${{env.REPO_NAME}}" "${unstable}"
            docker push "${unstable}"
          else
            : "No DOCKER_TOKEN, skipping push to DockerHub"
            exit 1
          fi
      - name: Push stable release to dockerhub on tags only
        if: ${{  github.ref_type }} == "tag"
        run: |
          if [[ -n "$DOCKERHUB_TOKEN" ]]; then

            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME " --password-stdin

            : "Pushing stable and latest versions to DockerHub for latest and  ${{  github.ref_name }}"

            latest="${{env.USER_NAME}}/${{env.REPO_NAME}}:latest"
            docker tag "${unstable}" "${latest}"
            docker push "${latest}"
            tagged_release="${{env.USER_NAME}}/${{env.REPO_NAME}}:${{  github.ref_name }}"
            docker tag "${unstable}" "${tagged_release}"
            docker push "${tagged_release}"

          else
              : "No DOCKER_TOKEN, skipping push to DockerHub"
              exit 1
          fi
